<center>
<img src="https://habrastorage.org/files/fd4/502/43d/fd450243dd604b81b9713213a247aa20.jpg">
    
## [mlcourse.ai](mlcourse.ai) – Open Machine Learning Course 

<center>Author: [Yury Kashnitskiy](http://yorko.github.io) <br>
Translated and edited by [Sergey Isaev](https://www.linkedin.com/in/isvforall/), [Artem Trunov](https://www.linkedin.com/in/datamove/), [Anastasia Manokhina](https://www.linkedin.com/in/anastasiamanokhina/), and [Yuanyuan Pao](https://www.linkedin.com/in/yuanyuanpao/) <br>All content is distributed under the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

# <center> Assignment #1 (demo)
## <center>  Exploratory data analysis with Pandas

**In this task you should use Pandas to answer a few questions about the [Adult](https://archive.ics.uci.edu/ml/datasets/Adult) dataset. (You don't have to download the data – it's already here). Choose the answers in the [web-form](https://docs.google.com/forms/d/1uY7MpI2trKx6FLWZte0uVh3ULV4Cm_tDud0VDFGCOKg). This is a demo version of an assignment, so by submitting the form, you'll see a link to the solution .ipynb file.**

Unique values of all features (for more information, please see the links above):
- `age`: continuous.
- `workclass`: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- `fnlwgt`: continuous.
- `education`: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- `education-num`: continuous.
- `marital-status`: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- `occupation`: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- `relationship`: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- `race`: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- `sex`: Female, Male.
- `capital-gain`: continuous.
- `capital-loss`: continuous.
- `hours-per-week`: continuous.
- `native-country`: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- `salary`: >50K,<=50K

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
data = pd.read_csv("/content/drive/MyDrive/Collab/adult.data.csv")
data.head()

   age         workclass  fnlwgt  ... hours-per-week  native-country salary
0   39         State-gov   77516  ...             40   United-States  <=50K
1   50  Self-emp-not-inc   83311  ...             13   United-States  <=50K
2   38           Private  215646  ...             40   United-States  <=50K
3   53           Private  234721  ...             40   United-States  <=50K
4   28           Private  338409  ...             40            Cuba  <=50K

[5 rows x 15 columns]

**1. How many men and women (*sex* feature) are represented in this dataset?**

In [14]:
len(data[data['sex'] == 'Female'])

10771

In [15]:
len(data[data['sex'] == 'Male'])

21790

**2. What is the average age (*age* feature) of women?**

In [16]:
data3 = data[data['sex'] == 'Female']
data3["age"].mean()

36.85823043357163

**3. What is the percentage of German citizens (*native-country* feature)?**

In [18]:
data3 = (data[data['native-country'] == 'Germany'])
(len(data3)*1.0/len(data)*1.0)* 100

0.42074874850281013

**4-5. What are the mean and standard deviation of age for those who earn more than 50K per year (*salary* feature) and those who earn less than 50K per year? **

In [19]:
data3 = (data[data['salary'] == '>50K'])
data3['age'].mean()

44.24984058155847

In [20]:
data3["age"].std()

10.51902771985177

In [21]:
data4 = (data[data['salary'] == '<=50K'])
data4['age'].mean()

36.78373786407767

In [22]:
data4['age'].std()

14.020088490824813

**6. Is it true that people who earn more than 50K have at least high school education? (*education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* or *Doctorate* feature)**

In [23]:
data5 = data[(data['salary'] == '>50K')
        & ((data['education'] == 'Bachelors')
        | (data['education'] == 'Prof-school')
        | (data['education'] == 'Assoc-acdm')
        | (data['education'] == 'Assoc-voc')
        | (data['education'] == 'Masters')
        | (data['education'] == 'Doctorate'))]

data7 = (data[data['salary'] == '>50K'])

len(data7) - len(data5)

3306

**7. Display age statistics for each race (*race* feature) and each gender (*sex* feature). Use *groupby()* and *describe()*. Find the maximum age of men of *Amer-Indian-Eskimo* race.**

In [24]:
data3 = data.groupby(['race'])['age'].describe()
data3

                      count       mean        std   min   25%   50%   75%   max
race
Amer-Indian-Eskimo    311.0  37.173633  12.447130  17.0  28.0  35.0  45.5  82.0
Asian-Pac-Islander   1039.0  37.746872  12.825133  17.0  28.0  36.0  45.0  90.0
Black                3124.0  37.767926  12.759290  17.0  28.0  36.0  46.0  90.0
Other                 271.0  33.457565  11.538865  17.0  25.0  31.0  41.0  77.0
White               27816.0  38.769881  13.782306  17.0  28.0  37.0  48.0  90.0

**8. Among whom is the proportion of those who earn a lot (>50K) greater: married or single men (*marital-status* feature)? Consider as married those who have a *marital-status* starting with *Married* (Married-civ-spouse, Married-spouse-absent or Married-AF-spouse), the rest are considered bachelors.**

In [25]:
data5 = data[(data['salary'] == '>50K')
        & ((data['marital-status'] == 'Married-civ-spouse')
        | (data['marital-status'] == 'Married-spouse-absent')
        | (data['marital-status'] == 'Married-AF-spouse'))]

data7 = (data[data['salary'] == '>50K'])

len(data7) - len(data5)

1105

**9. What is the maximum number of hours a person works per week (*hours-per-week* feature)? How many people work such a number of hours, and what is the percentage of those who earn a lot (>50K) among them?**

In [26]:
data7 = data['hours-per-week'].max()

In [27]:
data8 = data[data['hours-per-week'] == data['hours-per-week'].max()]
len(data8)

85

In [28]:
data9 = data[(data['salary'] == '>50K')
        & (data['hours-per-week'] == data['hours-per-week'].max())]
len(data9) * 100 / len(data8)

29.41176470588235

**10. Count the average time of work (*hours-per-week*) for those who earn a little and a lot (*salary*) for each country (*native-country*). What will these be for Japan?**

In [29]:
print(data.groupby(['native-country', 'salary'])['hours-per-week'].describe())
print(data.loc[data['native-country']=='Japan'].groupby(['native-country', 'salary'])['hours-per-week'].describe())

                        count       mean        std  ...   50%   75%   max
native-country salary                                ...
?              <=50K    437.0  40.164760  12.817002  ...  40.0  45.0  99.0
               >50K     146.0  45.547945  10.202827  ...  40.0  50.0  80.0
Cambodia       <=50K     12.0  41.416667   3.088346  ...  40.0  40.5  50.0
               >50K       7.0  40.000000   0.000000  ...  40.0  40.0  40.0
Canada         <=50K     82.0  37.914634  13.012056  ...  40.0  40.0  70.0
...                       ...        ...        ...  ...   ...   ...   ...
United-States  >50K    7171.0  45.505369  11.025092  ...  40.0  50.0  99.0
Vietnam        <=50K     62.0  37.193548  12.422664  ...  40.0  40.0  77.0
               >50K       5.0  39.200000   1.788854  ...  40.0  40.0  40.0
Yugoslavia     <=50K     10.0  41.600000  11.305849  ...  40.0  40.0  66.0
               >50K       6.0  49.500000  11.202678  ...  46.0  58.0  65.0

[82 rows x 8 columns]
                       count       mean        std  ...   50%   75%   max
native-country salary                               ...
Japan          <=50K    38.0  41.000000  11.902759  ...  40.0  41.5  65.0
               >50K     24.0  47.958333  16.120414  ...  42.5  50.0  99.0

[2 rows x 8 columns]